version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
        - backend

  angular:
    image: chadha122/angulardevops:tag
    environment:
      API_BASE_URL: http://spring:8087/ # Update the API base URL to use the service name instead of the IP address
    ports:
      - "8081:80"
      - "4200:4200"
    restart: always
    depends_on:
      - spring
    networks:
      - frontend

  spring:
    image: chadha122/springdevops:tag
    restart: on-failure
    ports:
      - "8088:8088"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://db:3306/devops?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "root",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    depends_on:
      - db
    stdin_open: true
    networks:
      - frontend
      - backend
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - backend
    depends_on:
      - db

networks:
  frontend:
  backend:

volumes:
  db_data: {}
